---
title: "EM_GaussianMixtureModel"
author: "Zhechao"
date: "November 2, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

This is a demonstrative file of how to solve a simple-case Gaussian Mixture Model with EM algorithm.  
In this particular case, we estimate a mixture of 3 Gaussians using EM

1. Generate the 10000 samples
```{r}
set.seed(12345)
n = 50000
```
here we set the True distribution parameters

```{r}
Z = runif(n,min=0,max=1)
alpha1 = 0.4 
alpha2 = 0.25
alpha3 = 0.35
mu = c(0,1,-1)
sigma = c(2,1,3)
ind1 = which(Z<alpha1)
ind3 = which(Z>=(alpha1+alpha2))
```
generate the 1000 samples
```{r}
Y = rep(2,times = n)
Y[ind1] = 1
Y[ind3] = 3
X = rep(0,times = n) 
for (i in 1:n){
  m = mu[Y[i]]
  s = sigma[Y[i]]
  X[i] = rnorm(1,mean= m ,sd= s)
}
Y=factor(Y)
Truedata<-data.frame(cbind(X,Y))
Truedata<-Truedata[order(Y), ]
Truedata$Y=factor(Truedata$Y)
graph1<-ggplot(Truedata,aes(x=X,fill=Y))+geom_density(alpha=0.3)+xlim(c(-12,+12))
graph1
```
```{r}
graph2<-ggplot(Truedata,aes(x=X))+geom_density(alpha=0.3)+xlim(c(-12,+12))
graph2
```

2.set a starting point for EM-algorithm  
```{r}
alpha1_0 = 0.43
alpha2_0 = 0.26
alpha3_0 = 0.33

mu1_0 = 0.2
mu2_0 = 1.3
mu3_0 = -1.2

sigma1_0 = 1.8
sigma2_0 = 0.9
sigma3_0 = 3.3

## The first time set the initial value
alpha_t = c(alpha1_0,alpha2_0,alpha3_0)

mu_t = c(mu1_0,mu2_0,mu3_0)

sigma_t = c(sigma1_0,sigma2_0,sigma3_0)
##setup for alpha^(t+1), mu^(t+1), sigma^(t+1)
alpha_t_1 = c(0,0,0)
mu_t_1 = c(0,0,0)
sigma_t_1 = c(0,0,0)
```

3.Running EM algorithm  
```{r include=FALSE}
h = matrix(0,nrow = n, ncol = 3)##h_{ij} = E[Zij|Xi] 

nonstop = 1 ## Control While loop, stop when nonstop = 0

##Stop criteria 
threshold = 0.5*10^(-4)
iter=0
mu_array=c(mu_t)
sigma_array=c(sigma_t)
alpha_array=c(alpha_t)
delta_array=c()

while(nonstop){
  print(iter)
  for(i in 1:n){
    sum_f_theta = dnorm(X[i],mean = mu_t[1], sd = sigma_t[1])*alpha_t[1] + dnorm(X[i],mean = mu_t[2], sd = sigma_t[2])*alpha_t[2] + dnorm(X[i],mean = mu_t[3], sd = sigma_t[3])*alpha_t[3] 
    for(j in 1:3){
      h[i,j] = (dnorm(X[i],mean = mu_t[j], sd = sigma_t[j])*alpha_t[j])/(sum_f_theta)
    }
  }
  ## M - step
  for (l in 1:3){
    mu_t_1[l] = sum(h[,l]*X)/sum(h[,l])
    sigma_t_1[l] = sqrt(sum(h[,l]*(X - mu_t_1[l])^2)/sum(h[,l]))
    alpha_t_1[l] = sum(h[,l])/n
  }
  
  nonstop = max(abs(mu_t_1-mu_t),abs(sigma_t_1-sigma_t),abs(alpha_t_1-alpha_t))>threshold
  #print("loss:")
  #print(max(abs(mu_t_1-mu_t),abs(sigma_t_1-sigma_t),abs(alpha_t_1-alpha_t)))
  delta_array=c(delta_array,max(abs(mu_t_1-mu_t),abs(sigma_t_1-sigma_t),abs(alpha_t_1-alpha_t)))
  mu_t = mu_t_1
  sigma_t = sigma_t_1
  alpha_t = alpha_t_1
  mu_array=c(mu_array,mu_t)
  sigma_array=c(sigma_array,sigma_t)
  salpha_array=c(alpha_array,alpha_t)
  iter=iter+1
}
```
```{r}
print('Estimate of Mu')
print(mu_t)  ##EM estimate of mu
print('Estimate of Sigma')
print(sigma_t)  ##EM estimate of sigma
print('Estimate of Alpha')
print(alpha_t)  ##EM estimate of alpha
```

```{r include=False}
x = seq(from= -10, to = 10, by = 0.02)
#f = rep(0,length(x))

f = alpha1*dnorm(x,mean = mu[1],sd = sigma[1])+alpha2*dnorm(x,mean = mu[2],sd = sigma[2])+alpha3*dnorm(x,mean = mu[3],sd = sigma[3])

estimate = alpha_t[1]*dnorm(x,mean=mu_t[1],sd=sigma_t[1])
           +alpha_t[2]*dnorm(x,mean = mu_t[2],sd = sigma_t[2])
           +alpha_t[3]*dnorm(x,mean = mu_t[3],sd = sigma_t[3])
```

```{r}
df=data.frame(x,estimate)
graph3<-ggplot(data=df,aes(x,estimate))+geom_line()+geom_line(aes(x,f),colour='purple')
graph3
```

```{r}
graph4<-ggplot(data=df,aes(x,dnorm(x,mean = mu[3],sd = sigma[3])))+geom_line()+geom_line(data=df,aes(x,dnorm(x,mean = mu[2],sd = sigma[2])))+geom_line(data=df,aes(x,dnorm(x,mean = mu[1],sd = sigma[1])))
graph4
```

